env:
  global:
  - CC_TEST_REPORTER_ID=83baad8519999a5b5e6d714d446637d03275c0314a11cb5fc61d0f410105e633
language: ruby
rvm:
- 2.6.5
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rake
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: heroku
  api_key:
    secure: lJMJZy4FNgUMjRwYB95wbGN/dtndsLTWGNFr6o6L/fCQBPNwyaF+7q0Y4Ps10CpsgA6fgTfG65eEbTfnA2swvFc2rgWEyv4TuWjHFrqIMWc+kAE/V/Eq0AO5qdWEHF5VBKty/IIC3kcCILXjMuOia5AsiU0y/1Vnmac0PArI1YAq/V+2go451Rdm5enOzP9NsSTJAZkJo7P1ZeMwbhLVc8VVqdtCOwijpu5foLsZPUr9rxoZ8j+89X7PWaHpeJKv1zpdB1SRsI4XyxWY3QtKOMPd4oUxgJNeHR4VFVogsMQWRvSNFxmEUF9Alb404qwHFxh8le2Jjt8Da5MC9KI3WZVjCnniRG9M3R2SS6AN9C2rtC2Bf1VZC5/mk/Gyc//u7v6cBdDWPZyaHCFCd0F0q1IBqLK+/o4SgGMzgpB/Mhzqm+xNmFs5ntoK8vi/d/ANJQ1g6cwBingql5H893Dm0yRAScyhkSexnjOmwXMqKdsQl0XmbGBbhMPkij8uX5U4PuEYE0FEHoANOqOWjWPPMGjtwIUXKtU3KD0GO0LLi6p3odea0yRvo+5u7qAQUcehm3x3cYIrG2VVBf/7QBtJcZwgY5/+UoU4vRaEUdv2LTvOCQl3VqTJuyp6nV9BC9+4P+YM+QvtoVaUVRXaVrpFp7NTmJnmopQxXyD8M+1mOMQ=
